services:
  cat-weight-tracker: # Define a service named 'cat-weight-tracker'
    build: . # Build the Docker image using the Dockerfile in the current directory
    ports:
      - "8034:80" # Map port 8080 on your host to port 80 in the container
                 # You can change 8080 to any available port on your machine
    volumes:
      - data:/var/www/html/data # Mount a local 'data' directory to the container's '/var/www/html/data'
                                  # This will persist your SQLite database file even if the container is removed
volumes:
  data:
    name: catweight