services:
  cat-weight-tracker:
    container_name: cat-weight-tracker
    build: .
    restart: unless-stopped
    ports:
      - '8034:80'
    volumes:
      - data:/var/www/html/data

volumes:
  data:
    name: catweight
networks: {}
